apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hugo
  namespace: hugo
spec:
  components:
    - name: hugo-server
      type: webservice
      properties:
        image: ghcr.io/simon-boyer/simons-travel-blog:2022-08-28
        imagePullPolicy: Always
        ports:
          - port: 443
            expose: true