apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hugo
  namespace: hugo
spec:
  components:
    - name: hugo-server
      type: webservice
      properties:
        image: ghcr.io/simon-boyer/simons-travel-blog:2022-08-28
        imagePullPolicy: always
        ports:
          - port: 1313
            expose: true
      traits:
        - type: gateway
          properties:
            domain: blog.codegameeat.com
            http:
              "/": 1313
            class: traefik