apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hugo
  namespace: hugo
spec:
  components:
    - name: hugo-server
      type: webservice
      properties:
        image: ghcr.io/simon-boyer/simons-travel-blog:2022-08-28
        imagePullPolicy: Always
        ports:
          - port: 1313
            expose: true
      traits:
        - type: http-route
          properties:
            domains:
              - blog.codegameeat.com
            rules:
            - path:
                type: PathPrefix
                value: /
              port: 1313