name: Send emails

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: SendGrid
        uses: peter-evans/sendgrid-action@v1.0.1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}