name: Send emails

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: SendGrid
        uses: simon-boyer/sendgrid-action@test-v2
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}